apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-blue
  template:
    metadata:
      labels:
        app: app-blue
    spec:
      containers:
      - name: app
        image: myacrdemo1.azurecr.io/demoapptesting:{{TAG}}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-blue-service
  namespace: blue
spec:
  selector:
    app: app-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
